<?php

/**
 * @file
 * Contains hm.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function hm_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hm module.
    case 'help.page.hm':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('est') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function hm_theme() {
  return [
    'hm' => [
      'render element' => 'children',
    ],
  ];
}
