<?php

/**
 * @file
 * Contains universal_plantas.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function universal_plantas_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the universal_plantas module.
    case 'help.page.universal_plantas':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('modulo universal plantas') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function universal_plantas_theme() {
  return [
    'universal_plantas' => [
      'render element' => 'children',
    ],
  ];
}
